namespace FarmManagement.Application.DTOs.Expenses;

public sealed record PurchaseInvoiceResponse(
    Guid Id,
    Guid OrganizationId,
    Guid SupplierId,
    string SupplierName,
    Guid FarmId,
    string FarmName,
    string SupplierInvoiceNumber,
    DateOnly InvoiceDate,
    DateOnly? DueDate,
    Guid CurrencyId,
    string CurrencyCode,
    string CurrencySymbol,
    string? PaymentTerms,
    decimal Subtotal,
    decimal TaxAmount,
    decimal OtherCharges,
    decimal DiscountAmount,
    decimal TotalAmount,
    decimal AmountPaid,
    decimal OutstandingBalance,
    string Status,
    string PaymentStatus,
    string DueStatus,
    string ReceiptStatus,
    string? Notes,
    string? AttachmentReference,
    DateTimeOffset? PostedAt,
    Guid? PostedBy,
    DateTimeOffset? ReversedAt,
    Guid? ReversedBy,
    string? ReversalReason,
    DateTimeOffset CreatedAt,
    Guid CreatedBy,
    DateTimeOffset? UpdatedAt,
    IReadOnlyList<PurchaseInvoiceLineResponse> Lines);

public sealed record PurchaseInvoiceLineResponse(
    Guid Id,
    Guid PurchaseInvoiceId,
    string LineType,
    Guid? InventoryItemId,
    string? InventoryItemName,
    string? InventoryItemSku,
    Guid? ExpenseCategoryId,
    string? ExpenseCategoryName,
    string? Description,
    decimal? Quantity,
    Guid? StockUnitId,
    string? StockUnitCode,
    string? StockUnitName,
    decimal UnitPrice,
    decimal LineAmount,
    Guid? FarmAreaId,
    string? FarmAreaName,
    Guid? PlantationId,
    string? PlantationName,
    Guid? CropCycleId,
    string? CropCycleName,
    Guid? CropCycleStageId,
    string? CropCycleStageName,
    int SortOrder);

public sealed record CreatePurchaseInvoiceRequest(
    Guid SupplierId,
    Guid FarmId,
    string SupplierInvoiceNumber,
    DateOnly InvoiceDate,
    DateOnly? DueDate,
    Guid CurrencyId,
    string? PaymentTerms,
    decimal TaxAmount,
    decimal OtherCharges,
    decimal DiscountAmount,
    string? Notes,
    string? AttachmentReference,
    IReadOnlyList<CreatePurchaseInvoiceLineRequest> Lines);

public sealed record CreatePurchaseInvoiceLineRequest(
    string LineType,
    Guid? InventoryItemId,
    Guid? StockUnitId,
    decimal? Quantity,
    decimal? UnitPrice,
    Guid? ExpenseCategoryId,
    decimal? Amount,
    string? Description,
    Guid? FarmAreaId,
    Guid? PlantationId,
    Guid? CropCycleId,
    Guid? CropCycleStageId,
    int SortOrder = 0);

public sealed record UpdatePurchaseInvoiceRequest(
    Guid SupplierId,
    Guid FarmId,
    string SupplierInvoiceNumber,
    DateOnly InvoiceDate,
    DateOnly? DueDate,
    Guid CurrencyId,
    string? PaymentTerms,
    decimal TaxAmount,
    decimal OtherCharges,
    decimal DiscountAmount,
    string? Notes,
    string? AttachmentReference,
    IReadOnlyList<CreatePurchaseInvoiceLineRequest> Lines);

public sealed record ReversePurchaseInvoiceRequest(
    string Reason);

public sealed record PurchaseInvoiceFilter(
    string? Search = null,
    Guid? SupplierId = null,
    Guid? FarmId = null,
    string? Status = null,
    DateOnly? From = null,
    DateOnly? To = null,
    string? PaymentStatus = null,
    string? DueStatus = null,
    string? ReceiptStatus = null);
