using FarmManagement.Domain.Enums;

namespace FarmManagement.Application.DTOs.Sprays;

public sealed record SprayListQuery(
    Guid? FarmId = null,
    Guid? FarmAreaId = null,
    Guid? PlantationId = null,
    Guid? CropCycleId = null,
    Guid? CropCycleStageId = null,
    string? Status = null,
    Guid? TargetId = null,
    DateOnly? FromDate = null,
    DateOnly? ToDate = null,
    string? Search = null,
    bool IncludeOverdue = false,
    int PageNumber = 1,
    int PageSize = 20,
    string? SortBy = null,
    string? SortDirection = null);

public sealed record SprayListItemResponse(
    Guid Id,
    string? ReferenceNumber,
    Guid FarmId,
    string FarmName,
    Guid? FarmAreaId,
    string? FarmAreaName,
    Guid? PlantationId,
    string? PlantationName,
    Guid? CropCycleId,
    string? CropCycleName,
    Guid? CropCycleStageId,
    string? CropCycleStageName,
    SprayStatus Status,
    string StatusName,
    bool IsOverdue,
    DateOnly? PlannedDate,
    DateTimeOffset? ScheduledDateTime,
    DateTimeOffset? ActualApplicationDateTime,
    Guid? TargetId,
    string? TargetName,
    Guid? ApplicationMethodId,
    string? ApplicationMethodName,
    int ProductCount,
    DateTimeOffset CreatedAt);

public sealed record SprayProductDto(
    Guid Id,
    Guid InventoryItemId,
    string InventoryItemName,
    string? InventoryItemSku,
    Guid StockUnitId,
    string StockUnitName,
    string StockUnitSymbol,
    Guid? StorageLocationId,
    string? StorageLocationName,
    decimal? PlannedQuantity,
    decimal? ActualQuantity,
    string? Dosage);

public sealed record SprayDetailsResponse(
    Guid Id,
    string? ReferenceNumber,
    Guid OrganizationId,
    Guid FarmId,
    string FarmName,
    Guid? FarmAreaId,
    string? FarmAreaName,
    Guid? PlantationId,
    string? PlantationName,
    Guid? CropCycleId,
    string? CropCycleName,
    Guid? CropCycleStageId,
    string? CropCycleStageName,
    SprayStatus Status,
    string StatusName,
    bool IsOverdue,
    DateOnly? PlannedDate,
    DateTimeOffset? ScheduledDateTime,
    DateTimeOffset? ActualApplicationDateTime,
    decimal? PlannedArea,
    Guid? PlannedAreaUnitId,
    string? PlannedAreaUnitName,
    decimal? ActualTreatedArea,
    Guid? ActualTreatedAreaUnitId,
    string? ActualTreatedAreaUnitName,
    decimal? WaterQuantity,
    Guid? WaterUnitId,
    string? WaterUnitName,
    Guid? TargetId,
    string? TargetName,
    TargetType? TargetType,
    Guid? ApplicationMethodId,
    string? ApplicationMethodName,
    string? PurposeReason,
    string? CancellationReason,
    IReadOnlyList<SprayProductDto> Products,
    DateTimeOffset CreatedAt,
    Guid CreatedBy,
    DateTimeOffset? UpdatedAt,
    Guid? UpdatedBy);

public sealed record CreateSprayDraftRequest(
    Guid FarmId,
    Guid? FarmAreaId = null,
    Guid? PlantationId = null,
    Guid? CropCycleId = null,
    Guid? CropCycleStageId = null,
    DateOnly? PlannedDate = null,
    decimal? PlannedArea = null,
    Guid? PlannedAreaUnitId = null,
    decimal? WaterQuantity = null,
    Guid? WaterUnitId = null,
    Guid? TargetId = null,
    Guid? ApplicationMethodId = null,
    string? PurposeReason = null,
    IReadOnlyList<SprayProductItemRequest>? Products = null);

public sealed record UpdateSprayDraftRequest(
    Guid FarmId,
    Guid? FarmAreaId = null,
    Guid? PlantationId = null,
    Guid? CropCycleId = null,
    Guid? CropCycleStageId = null,
    DateOnly? PlannedDate = null,
    decimal? PlannedArea = null,
    Guid? PlannedAreaUnitId = null,
    decimal? WaterQuantity = null,
    Guid? WaterUnitId = null,
    Guid? TargetId = null,
    Guid? ApplicationMethodId = null,
    string? PurposeReason = null,
    IReadOnlyList<SprayProductItemRequest>? Products = null);

public sealed record SprayProductItemRequest(
    Guid InventoryItemId,
    decimal? PlannedQuantity = null,
    string? Dosage = null);
