import { ChangeDetectionStrategy, Component, DestroyRef, OnInit, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { forkJoin, finalize, of } from 'rxjs';
import { FarmManagementService } from '../../core/farm-management/farm-management.service';
import { getApiErrorMessage } from '../../core/models/api-error.model';

@Component({ selector: 'app-farm-editor-page', standalone: true, imports: [MatButtonModule, MatCardModule, MatFormFieldModule, MatInputModule, MatProgressSpinnerModule, MatSelectModule, ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
<div class="section-heading"><a mat-button routerLink="/farms">← Back to farms</a><p class="eyebrow">Farm details</p><h2>{{farmId?'Edit farm':'New farm'}}</h2></div>
@if(isLoading()){<div class="loading-state"><mat-spinner diameter="36"/></div>}@else{<mat-card><mat-card-content><form [formGroup]="form" (ngSubmit)="submit()"><div class="form-grid"><mat-form-field appearance="outline"><mat-label>Code</mat-label><input matInput formControlName="code"/>@if(form.controls.code.hasError('required')){<mat-error>Code is required.</mat-error>}</mat-form-field><mat-form-field appearance="outline"><mat-label>Name</mat-label><input matInput formControlName="name"/>@if(form.controls.name.hasError('required')){<mat-error>Name is required.</mat-error>}</mat-form-field><mat-form-field appearance="outline"><mat-label>Ownership</mat-label><mat-select formControlName="ownershipTypeId">@for(type of ownershipTypes();track type.id){<mat-option [value]="type.id">{{type.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Total area</mat-label><input matInput type="number" formControlName="totalArea" min="0"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Area unit</mat-label><mat-select formControlName="areaUnitId">@for(unit of units();track unit.id){<mat-option [value]="unit.id">{{unit.name}} ({{unit.symbol}})</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline" class="wide"><mat-label>Description</mat-label><textarea matInput rows="3" formControlName="description"></textarea></mat-form-field><mat-form-field appearance="outline"><mat-label>City</mat-label><input matInput formControlName="city"/></mat-form-field><mat-form-field appearance="outline"><mat-label>State</mat-label><input matInput formControlName="state"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Latitude</mat-label><input matInput type="number" formControlName="latitude" min="-90" max="90"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Longitude</mat-label><input matInput type="number" formControlName="longitude" min="-180" max="180"/></mat-form-field></div>@if(errorMessage()){<p class="form-error">{{errorMessage()}}</p>}<div class="form-actions"><a mat-button routerLink="/farms">Cancel</a><button mat-flat-button color="primary" [disabled]="isSubmitting()" type="submit">{{farmId?'Save changes':'Create farm'}}</button></div></form></mat-card-content></mat-card>}`, styles: [`:host{display:block}.section-heading{margin-bottom:20px}.section-heading h2{margin:4px 0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.wide{grid-column:1/-1}.form-actions{display:flex;justify-content:flex-end;gap:12px;margin-top:20px}.form-error{color:#b3261e}@media(max-width:640px){.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}}`] })
export class FarmEditorPageComponent implements OnInit {
  private readonly service=inject(FarmManagementService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly snack=inject(MatSnackBar);private readonly destroyRef=inject(DestroyRef);private readonly fb=inject(FormBuilder);readonly farmId=this.route.snapshot.paramMap.get('id');readonly isLoading=signal(true);readonly isSubmitting=signal(false);readonly errorMessage=signal<string|null>(null);readonly units=signal<readonly any[]>([]);readonly ownershipTypes=signal<readonly any[]>([]);readonly form=this.fb.group({code:['',[Validators.required,Validators.maxLength(50)]],name:['',[Validators.required,Validators.maxLength(200)]],description:[''],ownershipTypeId:['',[Validators.required]],totalArea:[null as number|null],areaUnitId:[null as string|null],city:[''],state:[''],latitude:[null as number|null],longitude:[null as number|null]});
  ngOnInit():void{forkJoin({farm:this.farmId?this.service.getFarm(this.farmId):of(null),units:this.service.listUnits(),ownership:this.service.listOwnershipTypes()}).pipe(takeUntilDestroyed(this.destroyRef),finalize(()=>this.isLoading.set(false))).subscribe({next:r=>{this.units.set(r.units);this.ownershipTypes.set(r.ownership);if(r.farm)this.form.patchValue({code:r.farm.code,name:r.farm.name,description:r.farm.description??'',ownershipTypeId:r.farm.ownershipTypeId,totalArea:r.farm.totalArea,areaUnitId:r.farm.areaUnitId,city:r.farm.city??'',state:r.farm.state??'',latitude:r.farm.latitude,longitude:r.farm.longitude});},error:e=>this.errorMessage.set(getApiErrorMessage(e,'Farm form data could not be loaded.'))});}
  submit():void{if(this.form.invalid){this.form.markAllAsTouched();return;}this.isSubmitting.set(true);const request=this.farmId?this.service.updateFarm(this.farmId,this.form.getRawValue()):this.service.createFarm(this.form.getRawValue());request.pipe(takeUntilDestroyed(this.destroyRef),finalize(()=>this.isSubmitting.set(false))).subscribe({next:()=>{this.snack.open(this.farmId?'Farm updated.':'Farm created.','Dismiss',{duration:3000});void this.router.navigateByUrl('/farms');},error:e=>this.errorMessage.set(getApiErrorMessage(e,'Farm could not be saved.'))});}
}
